### ISSUE TITLE
error when installing struct-lmm and running tests

### ISSUE THREAD

**Issue by annacuomo** [limix/struct-lmm#1]
====================================================================== test session starts ======================================================================
platform linux2 -- Python 2.7.13, pytest-3.1.2, py-1.4.34, pluggy-0.4.0
rootdir: /homes/acuomo/struct-lmm, inifile: setup.cfg
collecting 6 items / 1 errors
============================================================================ ERRORS =============================================================================
___________________________________________________ ERROR collecting struct_lmm/interpretation/optimal_rho.py ___________________________________________________
.eggs/py-1.4.34-py2.7.egg/py/_path/local.py:680: in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
E   ImportMismatchError: ('struct_lmm.interpretation.optimal_rho', '/homes/acuomo/struct-lmm/build/lib/struct_lmm/interpretation/optimal_rho.py', local('/homes/acuomo/struct-lmm/struct_lmm/interpretation/optimal_rho.py'))
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
==================================================================== 1 error in 6.80 seconds ====================================================================

**Comment by horta** [comment]
Hi @annacuomo =P I think that has been solved by now. Also, please, don't use Python 2.7 anymore: it is an ancient python version.
