### ISSUE TITLE
data_structlmm/env_norm.txt not found

### ISSUE THREAD

**Issue by wenzhenl** [limix/struct-lmm#10]
It seems the test data provided missed one file env_norm.txt

**Comment by rm18** [comment]
We have included an environmental matrix named env.txt which you can normalise.  This can be done through the command line by setting your input variable name as
EFILE0 = data_structlmm/env.txt
And your output variable name as
EFILE = data_structlmm/env_norm.txt
You can then use the norm_env function to normalise the original input file env.txt.  The normalised version of the environment matrix will be saved as env_norm.txt (this is not a file that we provide in the test data).
norm_env --in $EFILE0 --out $EFILE
We have recently made some changes to the package including the norm_env function, so the current documentation will not match your downloaded version of the package.  I would suggest that you update your downloaded version.
