### ISSUE TITLE
what's the missing value? 

### ISSUE THREAD

**Issue by caina89** [limix/struct-lmm#3]
I finally managed to get most of the things working I think! But it's throwing an error that there's missing values, though I think there aren't? Any idea what's the missing value it's complaining about? 

In [125]:     res_slmm = run_struct_lmm(reader, y, E, covs=covs,batch_size=100)
     ...: 

.. batch 0/9

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-125-75591403aab4> in <module>()
----> 1 res_slmm = run_struct_lmm(reader, y, E, covs=covs,batch_size=100)

/nfs/users/nfs_n/nc10/anaconda2/envs/struct-lmm/lib/python2.7/site-packages/struct_lmm-0.0.1-py2.7.egg/struct_lmm/runner/run_struct_lmm.pyc in run_struct_lmm(reader, pheno, env, covs, rhos, no_mean_to_one, batch_size, no_association_test, no_interaction_test, unique_variants)
    100             if not no_association_test:
    101                 # association test
--> 102                 _p, _ = slmm.score_2_dof(x)
    103                 _pv[snp] = _p
    104 

/nfs/users/nfs_n/nc10/anaconda2/envs/struct-lmm/lib/python2.7/site-packages/struct_lmm-0.0.1-py2.7.egg/struct_lmm/lmm/structlmm.pyc in score_2_dof(self, X, snp_dim, debug)
    215                 L = sp.hstack((rho**0.5*self.vec_ones.T, (1-rho)**0.5*self.Env))
    216                 xoL = X*L
--> 217                 PxoL = P(self.gp, xoL)
    218                 LToxPxoL = 0.5*sp.dot(xoL.T, PxoL)
    219                 eighQ, UQ = la.eigh(LToxPxoL)

/nfs/users/nfs_n/nc10/anaconda2/envs/struct-lmm/lib/python2.7/site-packages/struct_lmm-0.0.1-py2.7.egg/struct_lmm/lmm/structlmm.pyc in P(gp, M)
     14     if gp.mean.F is not None:
     15         WKiM = sp.dot(gp.mean.W.T, RV)
---> 16         WAiWKiM = sp.dot(gp.mean.W, gp.Areml.solve(WKiM))
     17         KiWAiWKiM = gp.covar.solve(WAiWKiM)
     18         RV-= KiWAiWKiM

/nfs/users/nfs_n/nc10/anaconda2/envs/struct-lmm/lib/python2.7/site-packages/limix_core/covar/covar_base.pyc in solve(self, M)
     71 
     72     def solve(self,M):
---> 73         return LA.cho_solve((self.chol(),True),M)
     74 
     75     def K_grad_i_dot(self, M, i):

/nfs/users/nfs_n/nc10/anaconda2/envs/struct-lmm/lib/python2.7/site-packages/scipy/linalg/decomp_cholesky.pyc in cho_solve(c_and_lower, b, overwrite_b, check_finite)
    162     (c, lower) = c_and_lower
    163     if check_finite:
--> 164         b1 = asarray_chkfinite(b)
    165         c = asarray_chkfinite(c)
    166     else:

/nfs/users/nfs_n/nc10/anaconda2/envs/struct-lmm/lib/python2.7/site-packages/numpy/lib/function_base.pyc in asarray_chkfinite(a, dtype, order)
   1213     if a.dtype.char in typecodes['AllFloat'] and not np.isfinite(a).all():
   1214         raise ValueError(
-> 1215             "array must not contain infs or NaNs")
   1216     return a
   1217 

## WHEN 

In [126]: np.isfinite(y).all()
Out[126]: True

In [127]: 

In [127]: np.isfinite(E).all()
Out[127]: True

In [128]: 

In [128]: np.isfinite(covs).all()
Out[128]: True

In [129]: 

In [129]: reader
Out[129]: <limix.data.bed_reader.BedReader instance at 0x7f233af3a050>

In [130]: reader.getGenotypes
Out[130]: <bound method BedReader.getGenotypes of <limix.data.bed_reader.BedReader instance at 0x7f233af3a050>>

In [131]: reader.getGenotypes()
Out[131]: 
array([[2, 2, 2, ..., 2, 2, 2],
       [2, 2, 2, ..., 2, 2, 2],
       [2, 2, 2, ..., 2, 2, 2],
       ..., 
       [2, 2, 2, ..., 2, 2, 2],
       [2, 2, 2, ..., 2, 2, 2],
       [2, 2, 2, ..., 2, 2, 2]])

In [132]: np.isfinite(reader.getGenotypes()).all()
Out[132]: True

**Comment by horta** [comment]
Hi @cani89 . I'm closing this as the struct-lmm interface has changed for better, so that error does not replicate.
