### ISSUE TITLE
error in testing 

### ISSUE THREAD

**Issue by caina89** [limix/struct-lmm#4]
Installed /nfs/users/nfs_n/nc10/bin/struct-lmm/.eggs/py-1.4.34-py2.7.egg
running build_ext
=========================================================================================================== test session starts ============================================================================================================
platform linux2 -- Python 2.7.13, pytest-3.1.2, py-1.4.34, pluggy-0.4.0
rootdir: /nfs/users/nfs_n/nc10/bin/struct-lmm, inifile: setup.cfg
collecting 6 items / 1 errors
================================================================================================================== ERRORS ==================================================================================================================
________________________________________________________________________________________ ERROR collecting struct_lmm/interpretation/optimal_rho.py _________________________________________________________________________________________
.eggs/py-1.4.34-py2.7.egg/py/_path/local.py:680: in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
E   ImportMismatchError: ('struct_lmm.interpretation.optimal_rho', '/nfs/users/nfs_n/nc10/bin/struct-lmm/build/lib/struct_lmm/interpretation/optimal_rho.py', local('/nfs/users/nfs_n/nc10/bin/struct-lmm/struct_lmm/interpretation/optimal_rho.py'))
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================================================================================= 1 error in 6.31 seconds ==========================================================================================================

**Comment by horta** [comment]
It has been solved (issue #1).
